/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import javax.swing.ImageIcon;
import br.com.ifba.curso.dao.CursoDao;
import br.com.ifba.curso.entity.Curso;
import java.util.List;
import javax.swing.JOptionPane;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joaol
 */
public class CursoListar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoListar.class.getName());
    private final CursoDao cursoDao;
    
    private ImageIcon iconeLixeira;
    private ImageIcon iconeEditar;
    
    public CursoListar() {
        initComponents();
        this.cursoDao = new CursoDao();

        // carrega os icones originais e já os redimensiona para 32x32
        iconeLixeira = redimensionarIcone("/images/icons8-lixo-50.png", 32, 32);
        iconeEditar = redimensionarIcone("/images/icons8-crie-um-novo-64.png", 32, 32);
        
        tblTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                int linha = tblTabela.getSelectedRow();
                int coluna = tblTabela.getSelectedColumn();
                
                // 1. Obter a lista de cursos para saber qual objeto corresponde à linha clicada
                List<Curso> listaCursos = cursoDao.findAll();
                Curso cursoSelecionado = listaCursos.get(linha);

                // 2. Lógica baseada na coluna clicada (índices 3 e 4 na nova estrutura)
                if (coluna == 3) { // Coluna REMOVER
                    int confirm = javax.swing.JOptionPane.showConfirmDialog(null, 
                            "Deseja remover o curso: " + cursoSelecionado.getNome() + "?");
                    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                        cursoDao.delete(cursoSelecionado.getId());
                        carregarDados(); // Atualiza a tabela
                    }
                } else if (coluna == 4) { // Coluna EDITAR
                    new CursoAtualizar(cursoSelecionado, CursoListar.this).setVisible(true);
                }
            }
        });
        
        carregarDados();
    }
    
    
    // método auxiliar para o código não ficar repetitivo
    private ImageIcon redimensionarIcone(String caminho, int largura, int altura) {
        ImageIcon iconeOriginal = new ImageIcon(getClass().getResource(caminho));
        java.awt.Image imagemRedimensionada = iconeOriginal.getImage().getScaledInstance(largura, altura, java.awt.Image.SCALE_SMOOTH);
        return new ImageIcon(imagemRedimensionada);
    }
    
    public void carregarDados() {
        String[] colunas = {"NOME CURSO", "CARGA HORÁRIA", "ATIVO", "REMOVER", "EDITAR"};

        DefaultTableModel modelo = new DefaultTableModel(null, colunas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Mantém a tabela não editável diretamente nas células
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                switch (columnIndex) {
                    case 2: return Boolean.class;          // Coluna ATIVO (Checkbox)
                    case 3: 
                    case 4: return javax.swing.Icon.class; // Colunas REMOVER e EDITAR (Ícones)
                    default: return super.getColumnClass(columnIndex);
                }
            }
        };

        try {
            List<Curso> lista = cursoDao.findAll();

            for (Curso c : lista) {
                modelo.addRow(new Object[]{
                    c.getNome(), 
                    c.getCargaHoraria(), // Atributo que você deve adicionar na classe Curso
                    c.isAtivo(),         // Atributo que você deve adicionar na classe Curso
                    iconeLixeira, 
                    iconeEditar
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar: " + e.getMessage());
        }

        tblTabela.setModel(modelo);
        tblTabela.setRowHeight(40);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2d = (java.awt.Graphics2D) g;

                // Define as cores
                java.awt.GradientPaint gp = new java.awt.GradientPaint(
                    0, 0, new java.awt.Color(1, 20, 64),
                    0, getHeight(), new java.awt.Color(56, 95, 185)
                );

                g2d.setPaint(gp);
                g2d.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        pnlTabela = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTabela = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnHomescreen = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(102, 255, 102));

        tblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NOME CURSO", "CARGA HORÁRIA", "ATIVO", "REMOVER", "EDITAR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblTabela);

        javax.swing.GroupLayout pnlTabelaLayout = new javax.swing.GroupLayout(pnlTabela);
        pnlTabela.setLayout(pnlTabelaLayout);
        pnlTabelaLayout.setHorizontalGroup(
            pnlTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );
        pnlTabelaLayout.setVerticalGroup(
            pnlTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );

        btnAdd.setBackground(new java.awt.Color(0, 0, 76));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-adicionar-50.png"))); // NOI18N
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnHomescreen.setText("Homescreen");

        txtPesquisa.setText("Procurar...");
        txtPesquisa.addActionListener(this::txtPesquisaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHomescreen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdd)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHomescreen, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        new CursoCadastrar(this).setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:                                    
        String termo = txtPesquisa.getText();

        // Verifica se há um termo válido para busca
        if (!termo.isEmpty() && !termo.equalsIgnoreCase("Procurar...")) {
            try {
                // CHAMADA DIRETA AO MÉTODO DO DAO
                List<Curso> resultados = cursoDao.findByNome(termo);

                DefaultTableModel modelo = (DefaultTableModel) tblTabela.getModel();
                modelo.setRowCount(0); // Limpa a tabela atual

                if (resultados.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Nenhum curso encontrado.");
                }

                for (Curso c : resultados) {
                    modelo.addRow(new Object[]{
                        c.getNome(), 
                        c.getCargaHoraria(), 
                        c.isAtivo(), 
                        iconeLixeira, 
                        iconeEditar
                    });
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro na busca: " + e.getMessage());
                e.printStackTrace();
            }
        } else {
            // Se vazio, recarrega tudo
            carregarDados();
            }
    }//GEN-LAST:event_txtPesquisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CursoListar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnHomescreen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlTabela;
    private javax.swing.JTable tblTabela;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
